CREATE TABLE IF NOT EXISTS users_level (
  id SERIAL PRIMARY KEY,
  level_id INT NOT NULL REFERENCES levels(id) ON UPDATE CASCADE ON DELETE CASCADE,
  user_id INT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);