CREATE TABLE IF NOT EXISTS tests_degree (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  test_id INT NOT NULL REFERENCES tests(id) ON UPDATE CASCADE ON DELETE CASCADE,
  degree INT NOT NULL,
  created_at TIMESTAMP DEFAULT timezone('UTC', now())
);